function AdminPanel({ prodotti, setProdotti, onClose }) {
      const modificaPrezzo = (id, nuovoPrezzo) => {
          setProdotti((attuali) =>
                attuali.map((prodotto) =>
                        prodotto.id === id
                                  ? {
                                                ...prodotto,
                                                              prezzo: Number(nuovoPrezzo),
                                                                          }
                                                                                    : prodotto
                                                                                          )
                                                                                              )
                                                                                                }

                                                                                                  return (
                                                                                                      <div className="admin-overlay">
                                                                                                            <section className="admin-panel">
                                                                                                                    <div className="admin-header">
                                                                                                                              <div>
                                                                                                                                          <p>AREA RISERVATA</p>
                                                                                                                                                      <h2>GESTIONE PREZZI</h2>
                                                                                                                                                                </div>

                                                                                                                                                                          <button onClick={onClose}>×</button>
                                                                                                                                                                                  </div>

                                                                                                                                                                                          <div className="admin-products">
                                                                                                                                                                                                    {prodotti.map((prodotto) => (
                                                                                                                                                                                                                <article className="admin-product" key={prodotto.id}>
                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                              <strong>{prodotto.nome}</strong>
                                                                                                                                                                                                                                                              <small>Prezzo al kg</small>
                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                          <label>
                                                                                                                                                                                                                                                                                                          €
                                                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                                                            type="number"
                                                                                                                                                                                                                                                                                                                                                              step="0.10"
                                                                                                                                                                                                                                                                                                                                                                                min="0"
                                                                                                                                                                                                                                                                                                                                                                                                  value={prodotto.prezzo}
                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(evento) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                        modificaPrezzo(
                                                                                                                                                                                                                                                                                                                                                                                                                                                              prodotto.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    evento.target.value
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </article>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button className="admin-close" onClick={onClose}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        SALVA E CHIUDI
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default AdminPanel